### ISSUE TITLE
ERROR 53

### ISSUE THREAD

**Issue by philipperemy** [isacikgoz/gitbatch#79] opened 2019-02-08 05:18 UTC
I was using the tool when this error happened:

```
ERRO[0053] application quitted with an unhandled error.  error="There is no job with given repoID"
```

**Comment by isacikgoz** [comment] 2019-02-11 13:47
thanks for the feedback @philipperemy Can you provide me the steps to reproduce this issue?

I suspect that the queue started before the app loaded all repositories.

**Comment by philipperemy** [comment] 2019-02-11 23:41
Hum not sure how I did that :)

**Comment by isacikgoz** [comment] 2019-05-16 11:56
I am closing this issue, both you and me are not able to reproduce it, if you face it again feel free to open a new issue.

**Closed by isacikgoz** 2019-05-16 11:56 UTC
Labels: question

**Comment by philipperemy** [comment] 2019-05-17 01:39
@isacikgoz ok!
